### ISSUE TITLE
could not compile

### ISSUE THREAD

**Issue by pkudemonhunter** [ooclab/otunnel#18]
╰─[:(] ➜  ./build-by-docker.sh
go build -v -ldflags "-s -X main.buildstamp=`date '+%Y-%m-%d_%H:%M:%S_%z'` -X main.githash=`git rev-parse HEAD`" -o otunnel
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/ecrypt
github.com/ooclab/otunnel/vendor/golang.org/x/sys/unix
github.com/ooclab/otunnel/vendor/github.com/ooclab/es
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/tunnel/common
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/util
github.com/ooclab/otunnel/pkg/proto/json
github.com/ooclab/otunnel/vendor/golang.org/x/crypto/pbkdf2
github.com/ooclab/otunnel/pkg/util
github.com/ooclab/otunnel/vendor/github.com/urfave/cli
github.com/ooclab/otunnel/vendor/golang.org/x/crypto/ssh/terminal
github.com/ooclab/otunnel/vendor/github.com/sirupsen/logrus
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/session
# github.com/ooclab/otunnel/vendor/github.com/ooclab/es/session
vendor/github.com/ooclab/es/session/manager.go:43:4: undefined: logrus.Errorf
vendor/github.com/ooclab/es/session/manager.go:49:3: undefined: logrus.Errorf
vendor/github.com/ooclab/es/session/manager.go:64:3: undefined: logrus.WithFields
vendor/github.com/ooclab/es/session/manager.go:64:21: undefined: logrus.Fields
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/tunnel/channel
# github.com/ooclab/otunnel/vendor/github.com/ooclab/es/tunnel/channel
vendor/github.com/ooclab/es/tunnel/channel/tcp.go:54:2: undefined: logrus.Debugf
vendor/github.com/ooclab/es/tunnel/channel/tcp.go:75:3: undefined: logrus.Errorf
vendor/github.com/ooclab/es/tunnel/channel/tcp.go:78:3: undefined: logrus.Errorf
vendor/github.com/ooclab/es/tunnel/channel/tcp.go:92:4: undefined: logrus.Warn
vendor/github.com/ooclab/es/tunnel/channel/tcp.go:106:5: undefined: logrus.Debugf
vendor/github.com/ooclab/es/tunnel/channel/tcp.go:110:5: undefined: logrus.Warnf
vendor/github.com/ooclab/es/tunnel/channel/udp.go:53:2: undefined: logrus.Debugf
vendor/github.com/ooclab/es/tunnel/channel/udp.go:66:3: undefined: logrus.Errorf
vendor/github.com/ooclab/es/tunnel/channel/udp.go:69:3: undefined: logrus.Errorf
vendor/github.com/ooclab/es/tunnel/channel/udp.go:83:4: undefined: logrus.Warn
vendor/github.com/ooclab/es/tunnel/channel/udp.go:83:4: too many errors
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gwind** [comment]
This is because we have too logrus:

- https://github.com/Sirupsen/logrus
- https://github.com/sirupsen/logrus

and the one is broken (maybe download vendor interrupt) , just have few files, history:

- [otunnel/vendor/github.com](https://github.com/ooclab/otunnel/tree/535a32ada5178debf2125204ef2212e9a8eee281/vendor/github.com)
- [otunnel/vendor/github.com/sirupsen/logrus](https://github.com/ooclab/otunnel/tree/535a32ada5178debf2125204ef2212e9a8eee281/vendor/github.com/sirupsen/logrus)

And now this is [fixed](https://github.com/ooclab/otunnel/commit/ac25f2c79af87d0cb7f2463bbf6c340eaef24129), thanks for your help !
